apiVersion: v1
kind: Service
metadata:
  name: node-exporter-nodeport
  namespace: monitoring
  labels:
    app: node-exporter
spec:
  type: NodePort
  selector:
    app: node-exporter
  ports:
    - name: metrics
      port: 9101        # ClusterIP service port
      targetPort: 9101  # Pod port
      nodePort: 30901   # NodePort (accessible on every node)
      protocol: TCP

